version: '3'

services:
  server:
    container_name: server
    image: bluenviron/mediamtx:latest-ffmpeg
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./gizmo.mp4:/video.mp4
    ports:
      - '8189:8189'
      - '8554:8554'
      - '1935:1935'
      - '8888:8888'
      - '8889:8889'
    # networks:
    #   - network_mode=host
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    depends_on:
      - stream

  stream:
    container_name: stream
    image: linuxserver/ffmpeg
    restart: always
    volumes:
      - ./gizmo.mp4:/video.mp4
    network_mode: host
    command:
      [
        '-re',
        '-stream_loop',
        '-1',
        '-i',
        'video.mp4',
        '-c',
        'copy',
        '-f',
        'rtsp',
        '-rtsp_transport',
        'tcp',
        'rtsp://localhost:8554/mystream',
      ]
